[0m14:04:06.983396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001483B3E7F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001483AFA0830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001483AC66150>]}


============================== 14:04:06.990877 | 33772144-28b7-4338-90e2-9c7a1b8bbb68 ==============================
[0m14:04:06.990877 [info ] [MainThread]: Running with dbt=1.10.2
[0m14:04:06.990877 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\rafae\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m14:04:06.990877 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\git\dbt_cursos\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:04:06.996409 [debug] [MainThread]: Command `dbt run` failed at 14:04:06.996409 after 0.23 seconds
[0m14:04:06.996409 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001483B8970E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001483B3E7F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014837DD3C80>]}
[0m14:04:06.996409 [debug] [MainThread]: Flushing usage events
[0m14:04:07.850729 [debug] [MainThread]: An error was encountered while trying to flush usage events
